[profile.default]
solc_version = "0.8.30"
optimizer = false
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]

[lint]
ignore = ["mixed-case-function"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
